const {app, BrowserWindow, ipcMain} = require('electron');
const fs = require('node:fs/promises');
const path = require('node:path');
let saved = {};
app.whenReady().then(async () => {
  ipcMain.handle('data:load', () => saved);
  ipcMain.handle('data:save', (_e, data) => { saved = data; });
  ipcMain.handle('dict:lookup',(_e,p)=>({entry:{term:p.term,ipa:'/həˈləʊ/',senses:[{pos:'word',definitions:[{text:'Test meaning',examples:[]}]}],idioms:[]}}));
  ipcMain.handle('translate:google',()=>({translation:'Test translation'}));
  ipcMain.handle('pronunciation:ensureModel',()=>({ok:true}));
  ipcMain.handle('pronunciation:saveRecording',()=>({id:require('node:crypto').randomUUID()}));
  ipcMain.handle('pronunciation:score',()=>({overallScore:90,phones:[]}));
  const win = new BrowserWindow({show:false, width:1280, height:960, webPreferences:{offscreen:true, backgroundThrottling:false, preload:path.resolve('preload.js'), contextIsolation:true}});
  win.webContents.on('console-message', (_e, level, text) => { if(level>=2) console.error(text); });
  await win.loadFile(path.resolve('renderer/index.html'));
  await win.webContents.executeJavaScript(`(async () => {
    await loadPersisted();
    const check=(ok,msg)=>{if(!ok)throw Error(msg)};
    const click=action=>{const el=document.querySelector('[data-lt="'+action+'"]');check(el,'Missing '+action);el.click()};
    const input=(el,value)=>{el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}))};
    const root=document.getElementById('section-listening');
    let spoken=[];
    window.speechSynthesis.speak=u=>spoken.push(u.text);
    const grade=Listening.grade;
    check(grade('Hello, WORLD!', 'hello world').correct,'case punctuation');
    check(grade('I like tea','I really like tea').score===67,'extra word');
    check(grade('I like tea','I tea').score===67,'missing word');
    check(grade('I like tea','I like coffee').diff[2].kind==='wrong','substitution');
    check(grade('I like tea','').score===0,'blank');
    check(grade("Don’t stop", "don't stop").correct,'apostrophe');
    document.getElementById('nav-listening').click();
    check(!root.hidden && document.getElementById('section-reading').hidden,'navigation');
    click('new');
    input(root.querySelector('#lt-title'),'My lesson');
    input(root.querySelector('[data-field="english"]'),'Good morning.');
    root.querySelector('#lt-form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));
    check(state.listeningLessons[0].sentences.length===1,'manual create');
    click('list');click('import');
    input(root.querySelector('#lt-json'),'{ broken');
    click('import-json');
    check(root.querySelector('#lt-import-error').textContent,'invalid JSON error');
    check(state.listeningLessons.length===1,'failed import atomic');
    const fixture={title:'Daily conversation',sentences:[
      {english:'Could you help me with this?',ipa:'/kʊd juː help miː wɪð ðɪs/',vietnamese:'Bạn có thể giúp tôi việc này không?'},
      {english:'I would like a cup of coffee.',ipa:'/aɪ wʊd laɪk ə kʌp əv ˈkɒfi/',vietnamese:'Tôi muốn một tách cà phê.'},
      {english:'See you tomorrow.',ipa:'/siː juː təˈmɒrəʊ/',vietnamese:'Hẹn gặp bạn ngày mai.'}
    ]};
    const transfer=new DataTransfer(); transfer.items.add(new File([JSON.stringify(fixture)],'lesson.json',{type:'application/json'}));
    const fileInput=root.querySelector('#lt-json-file');fileInput.files=transfer.files;fileInput.dispatchEvent(new Event('change',{bubbles:true}));
    await new Promise(r=>setTimeout(r,50));
    check(JSON.parse(root.querySelector('#lt-json').value).title===fixture.title,'file import read');
    let copied='';Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{copied=text}},configurable:true});click('copy-json');
    await Promise.resolve();check(JSON.parse(copied).sentences[0].english,'copy JSON sample');
    click('import-json');
    check(state.listeningLessons.length===2,'import');
    check(root.querySelector('#lt-start').disabled,'empty selection disabled');
    const boxes=root.querySelectorAll('[data-sentence]');
    boxes[0].click();boxes[1].click();
    check(root.querySelector('#lt-select-all').indeterminate,'partial select');
    click('start');
    check(spoken.length===1,'auto play');
    const first=spoken[0];
    check(!root.textContent.includes(first),'answer hidden');
    input(root.querySelector('#lt-answer'),first);click('play');
    check(spoken[1]===first,'replay same sentence');
    click('check');check(root.querySelector('#lt-feedback').textContent.includes('100%'),'check current');
    const scoredSentence=state.listeningLessons[0].sentences.find(s=>s.english===first);
    check(scoredSentence.bestScore===100,'best score saved');
    input(root.querySelector('#lt-answer'),'wrong answer');click('check');
    check(scoredSentence.bestScore===100,'lower score cannot overwrite best');
    input(root.querySelector('#lt-answer'),first);
    click('next');
    check(spoken[2]!==first,'no repeats');
    input(root.querySelector('#lt-answer'),'I do not know');
    click('results');
    check(root.querySelectorAll('.lt-result').length===2,'only selected results');
    check(root.textContent.includes('1/2 correct'),'aggregate correct count');
    click('review');check(root.querySelector('#lt-answer').value===first,'answer preserved');
    state.readings.push({id:99,type:'markdown',title:'Unrelated reading',body:'Unrelated content',highlights:[]});state.currentReadingId=99;
    state.dictionaryConfig.path='test-dictionary';
    const selectAnswer=()=>{const answer=root.querySelector('#lt-answer');answer.focus();answer.setSelectionRange(0,first.indexOf(' '));Listening.captureSelection()};
    selectAnswer();
    check(!document.getElementById('selection-menu').hidden,'listening selection menu');
    check(document.querySelector('#selection-menu .sel-swatch').hidden,'Reading highlights hidden');
    check(selectionContext(state.pendingSelection)===first,'listening context');
    const word=state.pendingSelection.text;
    document.getElementById('btn-sel-speak').click();check(spoken.at(-1)===word,'selected pronunciation');
    document.getElementById('btn-sel-lookup').click();
    for(let i=0;i<100&&state.lookupState?.status!=='done';i++)await new Promise(r=>setTimeout(r,10));
    check(state.lookupState?.term===word,'selected lookup');
    document.getElementById('btn-lookup-add').click();
    check(state.pendingWord.source.readingId===null&&state.pendingWord.source.lessonId,'vocabulary source isolation');closeAddToCollectionModal();
    selectAnswer();document.getElementById('btn-sel-translate').click();
    for(let i=0;i<100&&state.translateState?.status!=='done';i++)await new Promise(r=>setTimeout(r,10));
    check(state.translateState?.selection.source.lessonId,'selected translation');closeTranslateModal();
    selectAnswer();document.getElementById('btn-sel-pronounce').click();
    for(let i=0;i<100&&!state.pronunciationState?.modelReady;i++)await new Promise(r=>setTimeout(r,10));
    check(state.pronunciationState?.source.lessonId,'recording source');
    await savePronunciationTake(state.pronunciationState,encodeWavPCM16(new Float32Array(800),16000));
    check(state.listeningLessons[0].pronunciationRecordings.length===1,'lesson recording saved');
    check(!currentReading().pronunciationRecordings,'no Reading contamination');closePronunciationModal();
    click('recordings');check(document.querySelectorAll('[data-play-recording]').length===1,'saved recording reopen');closePronunciationModal();
    const reference=root.querySelector('[data-lt-selectable=reference]');
    root.querySelector('#lt-answer').blur();const range=document.createRange();range.selectNodeContents(reference);window.getSelection().removeAllRanges();window.getSelection().addRange(range);Listening.captureSelection();
    check(state.pendingSelection.source.field==='reference'&&state.pendingSelection.text===first,'revealed text selection');
    const OriginalContext=window.AudioContext;
    Object.defineProperty(navigator,'mediaDevices',{value:{getUserMedia:async()=>({getTracks:()=>[{stop(){}}]})},configurable:true});
    window.AudioContext=class{constructor(){this.sampleRate=16000;this.destination={}}createMediaStreamSource(){return{connect(){},disconnect(){}}}createScriptProcessor(){return{connect(){},disconnect(){}}}createGain(){return{gain:{value:0},connect(){},disconnect(){}}}close(){return Promise.resolve()}};
    const hotkey=()=>document.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyR',altKey:true,bubbles:true,cancelable:true}));
    hotkey();for(let i=0;i<100&&state.pronunciationState?.phase!=='recording';i++)await new Promise(r=>setTimeout(r,10));
    check(state.pronunciationState?.phase==='recording'&&state.pronunciationState.source.field==='reference','Listening Alt+R starts');
    pronunciationCapturedChunks=[new Float32Array(800)];hotkey();
    for(let i=0;i<100&&state.pronunciationState?.phase!=='done';i++)await new Promise(r=>setTimeout(r,10));
    check(state.pronunciationState?.phase==='done'&&state.pronunciationState.savedTake,'Listening Alt+R stops and saves');
    closePronunciationModal();window.AudioContext=OriginalContext;
    window.getSelection().removeAllRanges();hideSelectionMenu();
    click('results');click('detail');
    check(root.querySelector('thead').textContent.includes('Best Score')&&root.querySelector('tbody').textContent.includes('100%'),'best score column');
    root.querySelector('#lt-select-all').click();click('start');click('results');
    check(root.querySelectorAll('.lt-result').length===3,'select all');
    check(root.textContent.includes('3 unanswered'),'unanswered scored');
    const snapshot=JSON.stringify(state.listeningLessons);
    await new Promise(r=>setTimeout(r,50));
    state.listeningLessons=[];await loadPersisted();
    check(JSON.stringify(state.listeningLessons)===snapshot,'lesson persistence');
    check(state.listeningLessons[0].sentences.find(s=>s.english===first).bestScore===100,'best score after reload');
    click('detail');click('edit');input(root.querySelector('#lt-title'),'Updated lesson title');
    root.querySelector('#lt-form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));
    check(state.listeningLessons[0].sentences.find(s=>s.english===first).bestScore===100,'editing metadata preserves score');
    console.log('PASS: grading, create/import validation, select subset/all, audio/replay, no repeats, per-question/all results, persistence');
  })()`);
  console.log('PASS: Listening integration, JSON file import/sample copy, scoring, persistence');
  await new Promise(r=>setTimeout(r,400));
  await fs.writeFile(path.join(require('node:os').tmpdir(),'vocab-listening-results.png'),(await win.webContents.capturePage()).toPNG());
  app.exit(0);
}).catch(err=>{console.error(err);app.exit(1)});
setTimeout(()=>{console.error('Timeout');app.exit(1)},30000);
